server:
  port: 8080

spring:
  application:
    name: vnticket-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/vnticket
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  brevo:
    api-key: "xkeysib-..." # Điền API Key của Brevo vào đây
  jwt:
    secret: VNTicketSuperSecretKeyForJwtGenerationMustBeLongEnoughToBeSecureVNTicketSuperSecretKeyForJwtGenerationMustBeLongEnoughToBeSecure
    expirationMs: 86400000 # 5 minutes
    jwtRefreshExpirationMs: 864000000 # 1 day
  google:
    clientId: 626920740184-b50brg5oc6psqva23adt7f9a7632fhp4.apps.googleusercontent.com
  vnpay:
    tmnCode: JLQON1G3
    hashSecret: R1HINBAXZXBR7SOMK9IZEJBQTW3MT4WD
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:5173/payment-return
  reservation:
    ttlMinutes: 15
  cors:
    allowed-origins: http://localhost:5173
  cookie:
    secure: false
    sameSite: Lax

cloudinary:
  cloud-name: "dilx7nhbv"
  api-key: "342651966745924"
  api-secret: "cC3wjZ9ZtdQKTqL1eVrnxVJiphI"
